
server:
  port: 8080

spring:
  profiles:
    default: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password: postgres
    mapper-locations: classpath:/mapper/**/*.xml
    hikari:
      maximum-pool-size: 4

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

logging:
  level:
    root: info
